- name: Saving Postcheck Output
  copy:
    content: "{{ postcheck_output.results | map(attribute='stdout') | join('\n') }}"
    dest: "{{ filepath }}/postchecks/{{ ansible_hostname }}_{{ postcheck_file }}"